# Generated by Django 2.1.7 on 2019-03-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slub',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=True),
        ),
    ]
