# Generated by Django 2.1.7 on 2019-03-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
