# Generated by Django 2.1.7 on 2019-04-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_billingaddress1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingAddress1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingPostcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
